"""Codex CLI adapter: hook payloads (Bash, apply_patch) and generated execpolicy rules.

Codex PreToolUse hooks can deny but cannot open an approval prompt, so ASK is rendered as a
block with an explanation. Commands that merely need approval are also emitted as
`decision = "prompt"` execpolicy rules for use without the hook. An execpolicy approval
does not override a PreToolUse hook denial when both are enabled.
"""

import json
import re
import shlex
from pathlib import Path
from typing import TextIO

from devguard import __version__, commands
from devguard.adapters import existing_text
from devguard.model import Decision, FileChange, ToolCall, Verdict
from devguard.rules import RULES

NAME = "codex"
SHELL_TOOLS = ("Bash", "shell", "local_shell", "exec_command")
_HEADER = re.compile(r"^\*\*\* (Add|Update|Delete) File: (.+)$")
_MOVE = re.compile(r"^\*\*\* Move to: (.+)$")


def to_call(payload: dict, cwd: Path) -> ToolCall | None:
    tool = payload.get("tool_name")
    data = payload.get("tool_input") or {}
    if not isinstance(data, dict):
        raise ValueError("tool_input must be a JSON object")
    base = {"agent": NAME, "tool": str(tool), "cwd": str(cwd)}
    if tool in SHELL_TOOLS:
        return ToolCall(**base, command=_text(data.get("command"), shlex.join))
    if tool == "apply_patch":
        patch = _text(data.get("command") or data.get("patch") or data.get("input"), "\n".join)
        return ToolCall(**base, changes=parse_patch(patch, cwd))
    return None


def parse_patch(text: str, cwd: Path) -> tuple[FileChange, ...]:
    changes: list[FileChange] = []
    current: dict | None = None

    def flush() -> None:
        if current is None:
            return
        if current["kind"] == "Delete":
            path = current["path"]
            changes.append(FileChange(path, existing_text(cwd, path), "", deleted=True))
            return
        removed, added = "\n".join(current["removed"]), "\n".join(current["added"])
        changes.append(FileChange(current["path"], removed, added))
        changes.extend(FileChange(target, "", added) for target in current["moves"])

    for line in text.splitlines():
        header = _HEADER.match(line)
        if header:
            flush()
            current = {"kind": header.group(1), "path": header.group(2).strip()}
            current.update(added=[], removed=[], moves=[])
            continue
        if current is None:
            continue
        move = _MOVE.match(line)
        if move:
            current["moves"].append(move.group(1).strip())
        elif line.startswith("***"):
            continue
        elif line.startswith("+"):
            current["added"].append(line[1:])
        elif line.startswith("-"):
            current["removed"].append(line[1:])
    flush()
    if not changes:
        raise ValueError("unrecognized apply_patch payload")
    return tuple(changes)


def emit(event: str, verdict: Verdict, stdout: TextIO, stderr: TextIO) -> int:
    if verdict.decision is Decision.ALLOW:
        return 0
    reason = verdict.reason()
    if verdict.decision is Decision.ASK:
        reason += (
            "\n[dev-guard] Codex hook은 확인 창을 띄울 수 없어 차단했습니다. 필요한 작업이면 "
            "사용자가 직접 실행하거나 ~/.dev-guard/policy.toml에서 규칙을 조정하세요."
        )
    stderr.write(reason + "\n")
    return 2


def render_rules() -> str:
    """Execpolicy rules mirroring the command guardrails that prefix matching can express."""
    lines = [
        f"# Generated by dev-guard {__version__}. Regenerate with `dev-guard codex-rules`;",
        "# manual edits are overwritten. Hooks still enforce the full policy.",
        "",
    ]

    def rule(pattern: list, rule_id: str) -> None:
        decision = "forbidden" if RULES[rule_id].default is Decision.DENY else "prompt"
        justification = f"{rule_id} {RULES[rule_id].title} ({RULES[rule_id].source})"
        lines.append(
            f"prefix_rule(pattern={json.dumps(pattern)}, decision={json.dumps(decision)}, "
            f"justification={json.dumps(justification, ensure_ascii=False)})"
        )

    for name in sorted(commands.NETWORK):
        rule([name], "DG-CMD-001")
    for name in sorted(commands.PRIVILEGE):
        rule([name], "DG-CMD-002")
    rule(["rm", ["-rf", "-fr", "-Rf", "-fR"]], "DG-CMD-003")
    for manager, subcommands in sorted(commands.HOST_PACKAGE_MANAGERS.items()):
        rule([manager, sorted(subcommands)], "DG-CMD-008")
    for manager, subcommands in sorted(commands.PACKAGE_INSTALLS.items()):
        rule([manager, sorted(subcommands)], "DG-CMD-005")
    for name in sorted(commands.DOWNLOAD_AND_RUN):
        rule([name], "DG-CMD-005")
    for python in ("python", "python3", "py"):
        rule([python, "-m", ["pip", "pip3"], "install"], "DG-CMD-005")
    rule(["uv", "add"], "DG-CMD-005")
    rule(["uv", "pip", "install"], "DG-CMD-005")
    rule(["git", "push"], "DG-CMD-006")
    rule(["git", "remote", ["add", "set-url"]], "DG-CMD-006")
    rule(["git", "reset", "--hard"], "DG-CMD-007")
    rule(["git", "clean"], "DG-CMD-007")
    return "\n".join(lines) + "\n"


def _text(value: object, join) -> str:
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return join(value)
    if isinstance(value, str) and value:
        return value
    raise ValueError("tool_input.command must be a non-empty string or list of strings")
